# Transformações de Dados

Nesta aula aprenderemos como modificar informações existentes, criar novas colunas, transformar textos, aplicar funções e combinar diferentes conjuntos de dados.

Essas transformações fazem parte do dia a dia de um Analista de Dados, pois normalmente os dados precisam ser preparados antes de serem analisados.

In [1]:
import pandas as pd
import numpy as np

# Criando novas colunas

Uma das operações mais comuns em um DataFrame é criar novas colunas.

Essas colunas podem ser resultado de cálculos, concatenação de textos ou qualquer outra operação realizada sobre os dados existentes.

In [2]:
dados = {
    "Nome": ["Ana", "Bruno", "Carlos", "Daniela"],
    "Idade": [18, 25, 32, 40],
    "Salario": [2200, 3500, 4800, 6100]
}

df = pd.DataFrame(dados)

df

      Nome  Idade  Salario
0      Ana     18     2200
1    Bruno     25     3500
2   Carlos     32     4800
3  Daniela     40     6100

## Criando uma coluna através de um cálculo

Podemos utilizar uma coluna existente para criar outra.

Neste exemplo vamos calcular um bônus correspondente a **10% do salário**.

In [3]:
df["Bonus"] = df["Salario"] * 0.10

df

      Nome  Idade  Salario  Bonus
0      Ana     18     2200  220.0
1    Bruno     25     3500  350.0
2   Carlos     32     4800  480.0
3  Daniela     40     6100  610.0

## Criando outra coluna utilizando colunas existentes

Também podemos combinar diferentes colunas para gerar novos valores.

Neste exemplo vamos calcular o salário total considerando o bônus.

In [4]:
df["Salario_Final"] = df["Salario"] + df["Bonus"]

df

      Nome  Idade  Salario  Bonus  Salario_Final
0      Ana     18     2200  220.0         2420.0
1    Bruno     25     3500  350.0         3850.0
2   Carlos     32     4800  480.0         5280.0
3  Daniela     40     6100  610.0         6710.0

## Criando colunas com textos

Nem toda coluna precisa ser numérica.

Também podemos criar informações em formato de texto.

In [5]:
df["Pais"] = "Brasil"

df

      Nome  Idade  Salario  Bonus  Salario_Final    Pais
0      Ana     18     2200  220.0         2420.0  Brasil
1    Bruno     25     3500  350.0         3850.0  Brasil
2   Carlos     32     4800  480.0         5280.0  Brasil
3  Daniela     40     6100  610.0         6710.0  Brasil

## Exercício

Utilizando o DataFrame acima:

1. Crie uma coluna chamada **Imposto** correspondente a **15%** do salário.

2. Crie uma coluna chamada **Salário Líquido**, considerando:

```
Salário - Imposto
```

3. Crie uma coluna chamada **Empresa**, preenchendo todos os registros com:

```
SENAI
```

In [6]:
# Escreva aqui o seu código
# 1. Crie uma coluna chamada **Imposto** correspondente a **15%** do salário.
df["Imposto"] = df["Salario"] * 0.15

#2. Crie uma coluna chamada **Salário Líquido**, considerando:
df["Salario_liquido"] = df["Salario"] - df["Imposto"]

#3. Crie uma coluna chamada **Empresa**, preenchendo todos os registros com:
df["Empresa"] = "SENAI"

df

,Nome,Idade,Salario,Bonus,Salario_Final,Pais,Imposto,Salario_liquido,Empresa
0,Ana,18,2200,220.0,2420.0,Brasil,330.0,1870.0,SENAI
1,Bruno,25,3500,350.0,3850.0,Brasil,525.0,2975.0,SENAI
2,Carlos,32,4800,480.0,5280.0,Brasil,720.0,4080.0,SENAI
3,Daniela,40,6100,610.0,6710.0,Brasil,915.0,5185.0,SENAI

# Transformação de textos

Durante a limpeza e preparação dos dados é muito comum encontrarmos textos com espaços extras, letras maiúsculas e minúsculas misturadas ou palavras escritas de formas diferentes.

O Pandas possui diversas funções para padronizar essas informações.

In [7]:
dados = {
    "Nome": [
        " ana ",
        "BRUNO",
        "cArLoS",
        " maria "
    ],
    "Cidade":[
        " blumenau ",
        "JOINVILLE",
        "jaraguá do sul",
        " POMERODE "
    ]
}

df = pd.DataFrame(dados)

df

      Nome          Cidade
0     ana        blumenau
1    BRUNO       JOINVILLE
2   cArLoS  jaraguá do sul
3   maria        POMERODE

## Removendo espaços com `str.strip()`

Muitas vezes os dados possuem espaços em branco no início ou no final dos textos.

Esses espaços podem causar problemas durante filtros, pesquisas e comparações.

A função **`str.strip()`** remove esses espaços automaticamente.

In [8]:
df["Nome"] = df["Nome"].str.strip()

df

     Nome          Cidade
0     ana       blumenau
1   BRUNO       JOINVILLE
2  cArLoS  jaraguá do sul
3   maria       POMERODE

### Exercício

Utilize a função `str.strip()` para remover os espaços existentes na coluna **Cidade**.

In [9]:
# Escreva aqui o seu código
df["Cidade"] = df["Cidade"].str.strip()
df

     Nome          Cidade
0     ana        blumenau
1   BRUNO       JOINVILLE
2  cArLoS  jaraguá do sul
3   maria        POMERODE

## Convertendo textos para letras minúsculas com `str.lower()`

A função **`str.lower()`** converte todos os caracteres de um texto para letras minúsculas.

Essa transformação é muito utilizada para padronizar informações antes de realizar comparações.

In [10]:
df["Nome"] = df["Nome"].str.lower()

df

     Nome          Cidade
0     ana        blumenau
1   bruno       JOINVILLE
2  carlos  jaraguá do sul
3   maria        POMERODE

### Exercício

Converta todos os valores da coluna **Cidade** para letras minúsculas.

In [12]:
# Escreva aqui o seu código
df["Cidade"] = df["Cidade"].str.lower()
df

     Nome          Cidade
0     ana        blumenau
1   bruno       joinville
2  carlos  jaraguá do sul
3   maria        pomerode

## Convertendo textos para letras maiúsculas com `str.upper()`

A função **`str.upper()`** converte todos os caracteres para letras maiúsculas.

Essa padronização pode facilitar a leitura dos dados ou atender a padrões adotados pela empresa.

In [13]:
df["Cidade"] = df["Cidade"].str.upper()

df

     Nome          Cidade
0     ana        BLUMENAU
1   bruno       JOINVILLE
2  carlos  JARAGUÁ DO SUL
3   maria        POMERODE

## Capitalizando textos com `str.title()`

A função **`str.title()`** deixa a primeira letra de cada palavra em maiúsculo e as demais em minúsculo.

Esse formato costuma ser utilizado para padronizar nomes de pessoas, cidades e empresas.

In [14]:
df["Nome"] = df["Nome"].str.title()

df

     Nome          Cidade
0     Ana        BLUMENAU
1   Bruno       JOINVILLE
2  Carlos  JARAGUÁ DO SUL
3   Maria        POMERODE

### Exercício

Utilize `str.title()` para padronizar a coluna **Cidade**.

In [16]:
# Escreva aqui o seu código
df["Cidade"] = df["Cidade"].str.title()
df

     Nome          Cidade
0     Ana        Blumenau
1   Bruno       Joinville
2  Carlos  Jaraguá Do Sul
3   Maria        Pomerode

## Substituindo partes de um texto com `str.replace()`

A função **`str.replace()`** permite substituir palavras ou caracteres dentro de um texto.

Ela é muito utilizada para corrigir erros de digitação ou padronizar informações.

In [17]:
dados = {
    "Cidade":[
        "Blumenal",
        "Joinvile",
        "Pomderode",
        "Blumenal"
    ]
}

df = pd.DataFrame(dados)

df

      Cidade
0   Blumenal
1   Joinvile
2  Pomderode
3   Blumenal

In [18]:
df["Cidade"] = df["Cidade"].str.replace("Blumenal", "Blumenau")

df

      Cidade
0   Blumenau
1   Joinvile
2  Pomderode
3   Blumenau

Também podemos realizar várias substituições.

In [19]:
df["Cidade"] = df["Cidade"].str.replace("Joinvile", "Joinville")
df["Cidade"] = df["Cidade"].str.replace("Pomderode", "Pomerode")

df

      Cidade
0   Blumenau
1  Joinville
2   Pomerode
3   Blumenau

### Exercício

Corrija os nomes das frutas utilizando a função `str.replace()`.

In [26]:
dados_frutas = {
    "Frutas":[
        "Maca",
        "Larana",
        "Kywi",
        "Tomatte",
        "Bananna",
        "Limai",
        "Norango"
    ]
}

df = pd.DataFrame(dados_frutas)

df

    Frutas
0     Maca
1   Larana
2     Kywi
3  Tomatte
4  Bananna
5    Limai
6  Norango

In [27]:
# Escreva seu código aqui
df["Frutas"] = df["Frutas"].str.replace("Maca", "Maçã")
df["Frutas"] = df["Frutas"].str.replace("Larana", "Laranja")
df["Frutas"] = df["Frutas"].str.replace("Kywi", "Kiwi")
df["Frutas"] = df["Frutas"].str.replace("Tomatte", "Tomate")
df["Frutas"] = df["Frutas"].str.replace("Bananna", "Banana")
df["Frutas"] = df["Frutas"].str.replace("Limai", "Limão")
df["Frutas"] = df["Frutas"].str.replace("Norango", "Morango")
df

    Frutas
0     Maçã
1  Laranja
2     Kiwi
3   Tomate
4   Banana
5    Limão
6  Morango

# Conversão de tipos

Em alguns casos, os dados são carregados como texto, mesmo representando números ou datas.

Para realizar cálculos ou análises corretamente, precisamos converter esses valores para o tipo adequado.

In [28]:
dados = {
    "Idade":["18","25","30","41"],
    "Salario":["2500","3800","5100","6200"]
}

df = pd.DataFrame(dados)

df

  Idade Salario
0    18    2500
1    25    3800
2    30    5100
3    41    6200

In [30]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Idade    4 non-null      int64
 1   Salario  4 non-null      str
dtypes: int64(1), str(1)
memory usage: 196.0 bytes

In [ ]:
# Função astype() >> converte o tipo
df["Idade"] = df["Idade"].astype(int)

df

   Idade Salario
0     18    2500
1     25    3800
2     30    5100
3     41    6200

Também podemos converter a coluna **Salario**.

In [31]:
df["Salario"] = df["Salario"].astype(float)

df

   Idade  Salario
0     18   2500.0
1     25   3800.0
2     30   5100.0
3     41   6200.0

In [32]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Idade    4 non-null      int64
 1   Salario  4 non-null      float64
dtypes: float64(1), int64(1)
memory usage: 196.0 bytes

# Aplicando funções em colunas

Até agora utilizamos funções próprias do Pandas, como `str.strip()` e `str.title()`.

Entretanto, em muitas situações precisamos executar uma função personalizada para cada valor de uma coluna.

Para isso, utilizamos a função **`apply()`**.

O `apply()` percorre todos os valores de uma coluna e aplica uma função em cada um deles.

In [33]:
dados = {
    "Nome":["Ana","Bruno","Carlos","Daniela"],
    "Idade":[18,25,32,40],
    "Salario":[2200,3500,4800,6100]
}

df = pd.DataFrame(dados)

df

      Nome  Idade  Salario
0      Ana     18     2200
1    Bruno     25     3500
2   Carlos     32     4800
3  Daniela     40     6100

## Utilizando uma função pronta

O método `apply()` também pode utilizar funções já existentes do Python.

Neste exemplo, vamos converter todos os nomes para letras maiúsculas utilizando a função `str.upper`.

In [34]:
df["Nome"] = df["Nome"].apply(str.upper)

df

      Nome  Idade  Salario
0      ANA     18     2200
1    BRUNO     25     3500
2   CARLOS     32     4800
3  DANIELA     40     6100

## Utilizando funções `lambda`

Uma função **lambda** é uma função simples, escrita em apenas uma linha.

Ela é bastante utilizada quando a transformação é pequena e será utilizada apenas uma vez. Não conseguimos reaproveitar elas. Para criar uma função reutilizável, precisa ser uma função com DEF

In [35]:
dados = {
    "Nome":["Ana","Bruno","Carlos","Daniela"],
    "Salario":[2200,3500,4800,6100]
}

df = pd.DataFrame(dados)

df

      Nome  Salario
0      Ana     2200
1    Bruno     3500
2   Carlos     4800
3  Daniela     6100

Neste exemplo vamos aumentar todos os salários em **10%**.

In [36]:
df["Salario"] = df["Salario"].apply(
    lambda salario: salario * 1.10
)

df

      Nome  Salario
0      Ana   2420.0
1    Bruno   3850.0
2   Carlos   5280.0
3  Daniela   6710.0

Também podemos criar novas colunas utilizando funções lambda.

In [37]:
df["Bonus"] = df["Salario"].apply(
    lambda salario: salario * 0.10
)

df

      Nome  Salario  Bonus
0      Ana   2420.0  242.0
1    Bruno   3850.0  385.0
2   Carlos   5280.0  528.0
3  Daniela   6710.0  671.0

## Criando uma função com `def`

Quando uma transformação é maior ou será reutilizada várias vezes, podemos criar uma função utilizando `def`.

Depois, basta utilizar essa função juntamente com o `apply()`.

In [38]:
dados = {
    "Nome":["Ana","Bruno","Carlos","Daniela"],
    "Idade":[15,22,38,67]
}

df = pd.DataFrame(dados)

df

      Nome  Idade
0      Ana     15
1    Bruno     22
2   Carlos     38
3  Daniela     67

Vamos criar uma função para classificar as pessoas de acordo com a idade.

In [39]:
def classificar_idade(idade):

    if idade < 18:
        return "Menor de idade"

    elif idade < 65:
        return "Adulto"

    else:
        return "Idoso"

In [42]:
classificacao = classificar_idade(29)
print(classificacao)

Adulto

In [40]:
df["Categoria"] = df["Idade"].apply(classificar_idade)

df

      Nome  Idade       Categoria
0      Ana     15  Menor de idade
1    Bruno     22          Adulto
2   Carlos     38          Adulto
3  Daniela     67           Idoso

Observe que a função foi executada para cada valor da coluna **Idade**, gerando uma nova coluna chamada **Categoria**.

### Exercício

Crie uma função chamada **situacao()** que retorne:

- Jovem (até 29 anos)
- Adulto (30 até 59 anos)
- Sênior (65 anos ou mais)

Depois aplique essa função utilizando `apply()`.

In [ ]:
# Escreva seu código aqui
def situacao(idade):
    if idade <= 29:
        return "Jovem"
    elif idade <= 64:
        return "Adulto"
    else: 
        return "Sênior"


# Aplicando a função no Dataframe
df["Situacao"] = df["Idade"].apply(situacao)
df

      Nome  Idade       Categoria Situacao
0      Ana     15  Menor de idade    Jovem
1    Bruno     22          Adulto    Jovem
2   Carlos     38          Adulto   Adulto
3  Daniela     67           Idoso   Sênior

## Utilizando funções do NumPy

O `apply()` também pode utilizar funções disponíveis na biblioteca **NumPy**.

Isso permite realizar diversos cálculos matemáticos de forma simples.

In [51]:
dados = {
    "Numero":[4,9,16,25,36]
}

df = pd.DataFrame(dados)

df

   Numero
0       4
1       9
2      16
3      25
4      36

Neste exemplo vamos calcular a raiz quadrada utilizando a função `np.sqrt()`.

In [52]:
df["Raiz"] = df["Numero"].apply(np.sqrt)

df

   Numero  Raiz
0       4   2.0
1       9   3.0
2      16   4.0
3      25   5.0
4      36   6.0

Também podemos calcular o quadrado de cada valor utilizando `np.square()`.

In [53]:
df["Quadrado"] = df["Numero"].apply(np.square)

df

   Numero  Raiz  Quadrado
0       4   2.0        16
1       9   3.0        81
2      16   4.0       256
3      25   5.0       625
4      36   6.0      1296

# Transformações condicionais

Em muitas situações precisamos criar novas informações com base em uma condição.

Por exemplo:

- Identificar se uma pessoa é maior de idade.
- Classificar funcionários por faixa salarial.
- Informar se um aluno foi aprovado ou reprovado.

Essas transformações podem ser feitas utilizando **if/else**, funções **lambda** ou funções do **NumPy**.

In [54]:
dados = {
    "Nome":["Ana","Bruno","Carlos","Daniela","Eduardo"],
    "Idade":[15,18,24,16,35]
}

df = pd.DataFrame(dados)

df

      Nome  Idade
0      Ana     15
1    Bruno     18
2   Carlos     24
3  Daniela     16
4  Eduardo     35

## Utilizando `lambda` com `if` e `else`

Quando a condição é simples, podemos utilizar uma função **lambda** juntamente com um **if/else**.

A nova coluna será criada de acordo com a condição informada.

In [55]:
df["Maior_Idade"] = df["Idade"].apply(
    lambda idade: "Sim" if idade >= 18 else "Não"
)

df

      Nome  Idade Maior_Idade
0      Ana     15         Não
1    Bruno     18         Sim
2   Carlos     24         Sim
3  Daniela     16         Não
4  Eduardo     35         Sim

#### Outro exemplo

In [56]:
dados = {
    "Funcionario":["Ana","Bruno","Carlos","Daniela"],
    "Salario":[2200,3800,5200,7600]
}

df = pd.DataFrame(dados)

df

  Funcionario  Salario
0         Ana     2200
1       Bruno     3800
2      Carlos     5200
3     Daniela     7600

In [57]:
df["Faixa"] = df["Salario"].apply(
    lambda salario:
    "Alto"
    if salario >= 5000
    else "Normal"
)

df

  Funcionario  Salario   Faixa
0         Ana     2200  Normal
1       Bruno     3800  Normal
2      Carlos     5200    Alto
3     Daniela     7600    Alto

## Utilizando np.where()

Outra forma bastante utilizada para criar colunas condicionais é através da função **`np.where()`**.

Ela recebe três parâmetros:

- condição
- valor caso a condição seja verdadeira
- valor caso a condição seja falsa

Essa função é muito utilizada em projetos de análise de dados por ser simples e eficiente.

In [58]:
dados = {
    "Nome":["Ana","Bruno","Carlos","Daniela","Eduardo"],
    "Idade":[15,18,24,16,35]
}

df = pd.DataFrame(dados)

df

      Nome  Idade
0      Ana     15
1    Bruno     18
2   Carlos     24
3  Daniela     16
4  Eduardo     35

In [59]:
df["Maior_Idade"] = np.where(
    df["Idade"] >= 18,
    "Sim",
    "Não"
)

df

      Nome  Idade Maior_Idade
0      Ana     15         Não
1    Bruno     18         Sim
2   Carlos     24         Sim
3  Daniela     16         Não
4  Eduardo     35         Sim

Perceba que o resultado é exatamente o mesmo obtido utilizando `lambda`.

A principal diferença é que o `np.where()` trabalha diretamente sobre a coluna inteira, sem utilizar o `apply()`.

# Concatenando DataFrames

Até agora trabalhamos com apenas um DataFrame.

Entretanto, em muitos projetos é comum possuir informações separadas em diferentes tabelas.

Para unir esses DataFrames podemos utilizar a função **`pd.concat()`**.

Ela permite juntar tabelas pelas linhas ou pelas colunas.

In [60]:
import pandas as pd

clientes1 = pd.DataFrame({
    "ID":[1,2,3],
    "Nome":["Ana","Bruno","Carlos"]
})

clientes2 = pd.DataFrame({
    "ID":[4,5],
    "Nome":["Daniela","Eduardo"]
})

print(clientes1)
print(clientes2)

   ID    Nome
0   1     Ana
1   2   Bruno
2   3  Carlos
   ID     Nome
0   4  Daniela
1   5  Eduardo

## Concatenando pelas linhas (`axis=0`)

Quando utilizamos **`axis=0`**, as linhas de um DataFrame são adicionadas abaixo das linhas do outro.

Esse é o comportamento padrão da função `concat()`.

In [61]:
clientes = pd.concat([clientes1, clientes2])

clientes

   ID     Nome
0   1      Ana
1   2    Bruno
2   3   Carlos
0   4  Daniela
1   5  Eduardo

Observe que os índices foram mantidos.

Por isso aparecem índices repetidos.

Para criar uma nova numeração dos índices, podemos utilizar o parâmetro **`ignore_index=True`**.

In [63]:
clientes = pd.concat(
    [clientes1, clientes2],
    ignore_index=True
)

clientes

   ID     Nome
0   1      Ana
1   2    Bruno
2   3   Carlos
3   4  Daniela
4   5  Eduardo

## Concatenando pelas colunas (`axis=1`)

Também podemos unir DataFrames lado a lado.

Para isso utilizamos **`axis=1`**.

In [64]:
nomes = pd.DataFrame({
    "Nome":["Ana","Bruno","Carlos"]
})

idades = pd.DataFrame({
    "Idade":[18,25,30]
})

print(nomes)
print(idades)

     Nome
0     Ana
1   Bruno
2  Carlos
   Idade
0     18
1     25
2     30

In [65]:
pd.concat(
    [nomes, idades],
    axis=1
)

     Nome  Idade
0     Ana     18
1   Bruno     25
2  Carlos     30

Nesse caso, as colunas foram unidas.

É importante que ambos os DataFrames possuam a mesma quantidade de linhas.

# Relacionando DataFrames com `merge()`

Enquanto o `concat()` apenas junta tabelas, o **`merge()`** relaciona informações através de uma coluna em comum.

Esse comportamento é semelhante ao **PROCV** do Excel ou aos comandos **JOIN** utilizados em bancos de dados.

In [66]:
clientes = pd.DataFrame({
    "ID":[1,2,3,4],
    "Nome":[
        "Ana",
        "Bruno",
        "Carlos",
        "Daniela"
    ]
})

clientes

   ID     Nome
0   1      Ana
1   2    Bruno
2   3   Carlos
3   4  Daniela

In [67]:
pedidos = pd.DataFrame({
    "ID":[1,2,2,4],
    "Produto":[
        "Mouse",
        "Notebook",
        "Monitor",
        "Teclado"
    ]
})

pedidos

   ID   Produto
0   1     Mouse
1   2  Notebook
2   2   Monitor
3   4   Teclado

## Relacionando os DataFrames

Observe que ambos possuem a coluna **ID**.

Essa coluna será utilizada para relacionar os registros.

In [68]:
resultado = pd.merge(
    clientes,
    pedidos,
    on="ID"
)

resultado

   ID     Nome   Produto
0   1      Ana     Mouse
1   2    Bruno  Notebook
2   2    Bruno   Monitor
3   4  Daniela   Teclado

A coluna **ID** é chamada de **chave de relacionamento**, pois é utilizada para localizar informações correspondentes nos dois DataFrames.

## `how="inner"`

O tipo **Inner Join** retorna apenas os registros existentes nos dois DataFrames.

In [69]:
pd.merge(
    clientes,
    pedidos,
    on="ID",
    how="inner"
)

   ID     Nome   Produto
0   1      Ana     Mouse
1   2    Bruno  Notebook
2   2    Bruno   Monitor
3   4  Daniela   Teclado

## `how="left"`

Retorna todos os registros do DataFrame da esquerda.

Caso não exista correspondência, o valor será preenchido com **NaN**.

In [70]:
pd.merge(
    clientes,
    pedidos,
    on="ID",
    how="left"
)

   ID     Nome   Produto
0   1      Ana     Mouse
1   2    Bruno  Notebook
2   2    Bruno   Monitor
3   3   Carlos       NaN
4   4  Daniela   Teclado

## `how="right"`

Retorna todos os registros do DataFrame da direita.

In [71]:
pd.merge(
    clientes,
    pedidos,
    on="ID",
    how="right"
)

   ID     Nome   Produto
0   1      Ana     Mouse
1   2    Bruno  Notebook
2   2    Bruno   Monitor
3   4  Daniela   Teclado

## `how="outer"`

Retorna todos os registros dos dois DataFrames.

Quando não houver correspondência, os valores ausentes serão preenchidos com **NaN**.

In [72]:
pd.merge(
    clientes,
    pedidos,
    on="ID",
    how="outer"
)

   ID     Nome   Produto
0   1      Ana     Mouse
1   2    Bruno  Notebook
2   2    Bruno   Monitor
3   3   Carlos       NaN
4   4  Daniela   Teclado

## Exercício

Relacione os DataFrames **Funcionários** e **Departamentos** utilizando a coluna **ID**.

In [ ]:
funcionarios = pd.DataFrame({
    "ID":[1,2,3,4],
    "Nome":[
        "Ana",
        "Bruno",
        "Carlos",
        "Daniela"
    ]
})

departamentos = pd.DataFrame({
    "ID":[1,2,4],
    "Departamento":[
        "Financeiro",
        "RH",
        "TI"
    ]
})

In [ ]:
# Escreva aqui o seu código

# Concat x Merge

Embora ambos sejam utilizados para unir informações, eles possuem objetivos diferentes.

| Concat | Merge |
|---------|--------|
| Junta DataFrames | Relaciona DataFrames |
| Não precisa de uma chave | Precisa de uma chave em comum |
| Pode unir linhas ou colunas | Une registros correspondentes |
| Utiliza `axis=0` ou `axis=1` | Utiliza `on` e `how` |